import { existsSync, readFileSync, statSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'

/**
 * Marker comment to identify hooks generated by this plugin
 */
export const HOOK_MARKER = '# Generated by arere-plugin-githooks - do not edit manually'

/**
 * Supported git hook types
 */
export const SUPPORTED_HOOKS = [
  'pre-commit',
  'prepare-commit-msg',
  'commit-msg',
  'post-commit',
  'pre-push',
  'pre-rebase',
  'post-checkout',
  'post-merge',
] as const

export type HookType = (typeof SUPPORTED_HOOKS)[number]

/**
 * Find the git directory (.git) from the current working directory
 */
export function findGitDir(startPath: string = process.cwd()): string | null {
  let currentPath = resolve(startPath)
  const root = dirname(currentPath)

  while (currentPath !== root) {
    const gitPath = join(currentPath, '.git')
    if (existsSync(gitPath)) {
      // Check if it's a directory (normal repo) or file (worktree/submodule)
      const stat = statSync(gitPath)
      if (stat.isDirectory()) {
        return gitPath
      }
      // If it's a file, read the gitdir path from it
      if (stat.isFile()) {
        const content = readFileSync(gitPath, 'utf-8').trim()
        const match = content.match(/^gitdir: (.+)$/)
        if (match) {
          return resolve(currentPath, match[1])
        }
      }
    }
    currentPath = dirname(currentPath)
  }

  return null
}

/**
 * Get the hooks directory path
 */
export function getHooksDir(gitDir: string): string {
  return join(gitDir, 'hooks')
}

/**
 * Get the full path to a specific hook file
 */
export function getHookPath(gitDir: string, hookName: HookType): string {
  return join(getHooksDir(gitDir), hookName)
}

/**
 * Check if a hook file was generated by this plugin
 */
export function isPluginGeneratedHook(hookPath: string): boolean {
  if (!existsSync(hookPath)) {
    return false
  }

  try {
    const content = readFileSync(hookPath, 'utf-8')
    return content.includes(HOOK_MARKER)
  } catch {
    return false
  }
}

/**
 * Check if a hook file exists (regardless of who created it)
 */
export function hookExists(hookPath: string): boolean {
  return existsSync(hookPath)
}

/**
 * Generate hook script content
 */
export function generateHookScript(hookName: HookType): string {
  return `#!/bin/sh
${HOOK_MARKER}
npx arere run githooks-run ${hookName}
`
}

/**
 * Validate hook name
 */
export function isValidHookName(name: string): name is HookType {
  return SUPPORTED_HOOKS.includes(name as HookType)
}
